### PR TITLE
Update our fork with the original one

### PR DESCRIPTION
**Pull request by XVincentX**
Should solve the darwin issue

### CODE REVIEW

**Comment by Almad** [comment]
@XVincentX Hmm, thinking about it...do we still need the fork? I think it was originally created only because of CS support. @kuba-kubula @tu1ly @abtris

**Comment by abtris** [comment]
I think yes, `grunt` still doesn't have coffee-script 1.7+ support. Is planned to 0.5 version. We can merge this change if can help.

@XVincentX do you test this new version with Apiary app?

**Comment by XVincentX** [comment]
@Almad 
I am afraid we still have to keep our fork for coffeescript support.
There are a lot of PRs updating coffescript, but everytime they close it linking this issue: [#911](https://github.com/gruntjs/grunt/issues/911)

@abtris 
I did and looks ok, but I'd suggest to try at least another Darwin user before merge it. I am not so reliable :-1: 
I'll be happy to repeat all tests this night.

**Comment by kuba-kubula** [comment]
@XVincentX I see the coffee-script at the end of this PR in `grunt/package.json` file as 1.3.3 version.

That probably is not what we want, right?

**Comment by XVincentX** [comment]
@kuba-kubula Definitely not. I guess a simple merge from their master branch will not be enough.

**Pull request closed without merging**
