### PR TITLE
Update gruntjs to latest version

### PR DESCRIPTION
**Pull request by XVincentX**
Follow up from [#2](https://github.com/apiaryio/grunt/pull/2)

### CODE REVIEW

**Comment by XVincentX** [comment]
Tested on my machine again from clean environment.
If all will be good, then deploying on staging...

**Comment by XVincentX** [comment]
Version bumps are required to make it work with siblings dependencies (**grunt-coffeelint**)

**Comment by kuba-kubula** [comment]
@XVincentX @abtris Looks good from me

**Comment by abtris** [comment]
ok, look good for me too. Free to merge.

**Comment by XVincentX** [comment]
I would wait to have horsehead and API design library in private repositories so I'd be able to test entire flow before merging it.

**Pull request merged**
